ROOT_PATH = "C:/PyProjects/protein_intensity"
AMINOACID_PATH = ROOT_PATH + "/aminoacids/atoms"
AMINOACID_INFO_PATH = ROOT_PATH + "/aminoacids/data/amino_info_new.txt"
AMINOACID_INFO_PATH_LAR = ROOT_PATH + "/aminoacids/data/aminoacid_info_Lee&Richards.txt"
AMINOACID_INFO_PATH_KNIGHT = ROOT_PATH + "/aminoacids/data/aminoacid_data.txt"
OUTPUT_PATH = ROOT_PATH + "/outputs"
VECTORS_OUTPUT_PATH = ROOT_PATH + "/vectors/"
VECTOR_FILE_NAME = "vectors.txt"
AMINO_OUTPUT_FILE_NAME = "output.txt"
PDBS_PATH = ROOT_PATH + "/pdbs/"
WATER_PATH = PDBS_PATH + "waters/"
AMINO_PATH = PDBS_PATH + "aminos/"
VECTOR_COUNT = 20
VECTOR_DIF = 0.05
N_Z = 28
N_FI = 28
SX = 54.373000000000005
SY = 54.451
SZ = 69.41499999999999
INDENT = 8
